title = "baishen"
baseurl = "https://baishen.me/"
enableEmoji = true
defaultContentLanguage = "zh"
languageCode = "zh-CN"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
pygmentsCodeFences = true
pygmentsUseClasses = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Baishen"
  description = "Baishen Personal Site, focus on Distributed System, Database, Computational Advertising, Golang, Rust ..."
  googleAnalyticsId = "UA-143445286-1"

[params.assets]
  css = ["style", "syntax"]
  js  = []

[params.socialmedia]
  twitter = "https://twitter.com/b41sh"
  github  = "https://github.com/b41sh"
